# Generated by Django 4.2.28 on 2026-02-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="backgrounds/",
                        verbose_name="รูปพื้นหลัง",
                    ),
                ),
                (
                    "blur_amount",
                    models.IntegerField(default=10, verbose_name="ความเบลอ (px)"),
                ),
            ],
            options={
                "verbose_name": "ตั้งค่าเว็บไซต์",
                "verbose_name_plural": "ตั้งค่าเว็บไซต์",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "หมวดหมู่สินค้า", "verbose_name_plural": "หมวดหมู่สินค้า"},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "verbose_name": "รายการอาหาร",
                "verbose_name_plural": "รายการอาหาร",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "ออเดอร์", "verbose_name_plural": "รายการออเดอร์"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "รายการในออเดอร์",
                "verbose_name_plural": "รายการในออเดอร์",
            },
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="image_url",
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="menu_items/", verbose_name="รูปอาหาร"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อหมวดหมู่"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.category",
                verbose_name="หมวดหมู่",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="รายละเอียด"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="มีจำหน่าย"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อเมนู"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="ราคา"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="เวลาสั่ง"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอรับออเดอร์"),
                    ("cooking", "กำลังปรุง"),
                    ("ready", "พร้อมเสิร์ฟ"),
                    ("completed", "เสร็จสิ้น"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="pending",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.IntegerField(verbose_name="เลขโต๊ะ"),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="อัปเดตล่าสุด"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.menuitem",
                verbose_name="เมนู",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="จำนวน"),
        ),
    ]
