# Generated by Django 4.2.28 on 2026-02-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="restaurant_name",
            field=models.CharField(
                default="FoodPOS", max_length=255, verbose_name="ชื่อร้านอาหาร"
            ),
        ),
    ]
