# Generated by Django 4.2.28 on 2026-02-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_restaurant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="ราคารวมตัวเลือก ณ ตอนสั่ง",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ตัวเลือก/หมายเหตุ"),
        ),
        migrations.CreateModel(
            name="MenuItemOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        help_text="เช่น ความหวาน, ท็อปปิ้ง",
                        max_length=100,
                        verbose_name="กลุ่มตัวเลือก",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="เช่น ปกติ, หวานน้อย, ไข่มุก",
                        max_length=100,
                        verbose_name="ชื่อตัวเลือก",
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาบวกเพิ่ม",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="บังคับเลือก"),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.menuitem",
                        verbose_name="เมนู",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตัวเลือกเสริม",
                "verbose_name_plural": "ตัวเลือกเสริม",
            },
        ),
    ]
